In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv('imputed_combined_data_subset.csv')
df

id       color plastic type  400.133331  400.508789  400.884216  \
0    49  Transparan          PET   60.351364   60.512665   60.626610   
1    50  Trasnparan          PET   19.964344   20.043579   20.144825   
2    51  Transparan          PET   16.811512   16.893469   17.011232   
3    52       Putih          PET   75.843307   77.662079   79.593765   
4    53  Transparan          PET   37.036633   37.331455   37.493233   
..   ..         ...          ...         ...         ...         ...   
111  92       Putih           PP   22.010794   21.991207   22.081758   
112  94       Hijau         HDPE    5.387435    5.410059    5.418447   
113  96       Merah           PP    4.756849    4.715742    4.700873   
114  97  Transparan         LDPE   17.668196   17.732800   17.771029   
115  99  Transparan          PET   31.800541   31.763964   31.759115   

     401.259613  401.634949  402.010254  402.385559  ...  897.136108  \
0     60.735283   60.927467   61.144253   61.224869  ...   88.963318   
1     20.212513   20.396099   20.504927   20.559423  ...   47.218098   
2     17.055092   17.121126   17.187664   17.169941  ...   78.036636   
3     81.647659   83.815521   86.104065   88.202301  ...  274.305115   
4     37.620407   37.839821   38.025574   38.077957  ...   82.184387   
..          ...         ...         ...         ...  ...         ...   
111   22.051718   22.061535   22.068146   22.145014  ...   49.122322   
112    5.407332    5.420845    5.466297    5.499288  ...   26.037668   
113    4.673644    4.645596    4.682441    4.700151  ...   28.666117   
114   17.798872   17.875439   17.889919   17.960592  ...   38.489670   
115   31.703302   31.680586   31.671595   31.696791  ...   38.233681   

     897.444946  897.753723  898.062439  898.371155  898.679749  898.988342  \
0     88.568047   87.360184   85.711304   84.398033   83.330544   83.080719   
1     46.385483   45.225742   44.367702   43.060097   41.979828   40.690384   
2     77.393188   76.098213   74.713531   73.149994   72.379059   71.532295   
3    272.992462  270.220642  267.294525  263.118225  260.135864  258.894653   
4     80.849472   79.362396   77.899857   75.991585   74.288727   73.514656   
..          ...         ...         ...         ...         ...         ...   
111   49.167603   49.366898   49.454952   49.123531   49.123661   48.800087   
112   25.950628   25.791368   25.497551   25.611464   25.750959   25.782856   
113   28.547102   28.645178   28.797882   29.070797   28.889616   29.291142   
114   38.483730   38.414333   38.063812   38.238804   38.381062   37.937153   
115   38.436432   38.190315   37.948792   38.430115   38.801701   39.300556   

     899.296814  899.605225  899.913696  
0     82.002800   81.560013   81.482407  
1     39.956558   39.300247   38.560486  
2     70.585815   70.333099   69.396652  
3    256.679901  255.601395  255.142395  
4     72.317429   70.758453   69.727409  
..          ...         ...         ...  
111   48.411701   47.173000   47.520115  
112   25.315954   25.219360   24.680397  
113   29.141523   28.926725   28.823387  
114   37.680748   37.689575   37.653881  
115   39.160873   38.909870   38.204308  

[116 rows x 1457 columns]

# Split

In [15]:
# split the data into training and testing sets
from sklearn.model_selection import train_test_split
X = df.drop(['color', 'id', 'plastic type'], axis=1)\
# y = df['color']
y = df['plastic type']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# SVM

In [17]:
# do svm
from sklearn.svm import SVC

svm = SVC(kernel='linear')
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)

# evaluate the model
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[0 1 0 0 0]
 [1 1 1 4 0]
 [1 0 1 1 0]
 [2 2 1 6 1]
 [0 1 0 0 0]]
              precision    recall  f1-score   support

        HDPE       0.00      0.00      0.00         1
        LDPE       0.20      0.14      0.17         7
         PET       0.33      0.33      0.33         3
          PP       0.55      0.50      0.52        12
          PS       0.00      0.00      0.00         1

    accuracy                           0.33        24
   macro avg       0.22      0.20      0.20        24
weighted avg       0.37      0.33      0.35        24

